[2023-07-30T20:00:15.839+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-07-30T20:00:15.863+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emrSteps.S6 scheduled__2023-07-30T19:00:00+00:00 [queued]>
[2023-07-30T20:00:15.893+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emrSteps.S6 scheduled__2023-07-30T19:00:00+00:00 [queued]>
[2023-07-30T20:00:15.894+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-30T20:00:15.918+0000] {taskinstance.py:1327} INFO - Executing <Task(EmrAddStepsOperator): S6> on 2023-07-30 19:00:00+00:00
[2023-07-30T20:00:15.938+0000] {standard_task_runner.py:57} INFO - Started process 3453 to run task
[2023-07-30T20:00:15.954+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'emrSteps', 'S6', 'scheduled__2023-07-30T19:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/emrSteps.py', '--cfg-path', '/tmp/tmpuq1rfgbm']
[2023-07-30T20:00:15.958+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask S6
[2023-07-30T20:00:16.001+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-30T20:00:16.085+0000] {task_command.py:410} INFO - Running <TaskInstance: emrSteps.S6 scheduled__2023-07-30T19:00:00+00:00 [running]> on host 484e6be077e8
[2023-07-30T20:00:16.102+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-07-30T20:00:16.243+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emrSteps' AIRFLOW_CTX_TASK_ID='S6' AIRFLOW_CTX_EXECUTION_DATE='2023-07-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-30T19:00:00+00:00'
[2023-07-30T20:00:16.307+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-07-30T20:00:16.308+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-07-30T20:00:17.095+0000] {emr.py:145} INFO - Adding steps to j-3EO35D3IB9FCU
[2023-07-30T20:00:17.191+0000] {emr.py:168} INFO - Steps ['s-00172627SETQ72QV9KP'] added to JobFlow
[2023-07-30T20:00:37.363+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/emr.py", line 152, in execute
    step_ids = emr_hook.add_job_flow_steps(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/emr.py", line 172, in add_job_flow_steps
    waiter.wait(
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/waiter.py", line 55, in wait
    Waiter.wait(self, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/waiter.py", line 388, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StepComplete failed: Max attempts exceeded
[2023-07-30T20:00:37.372+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=emrSteps, task_id=S6, execution_date=20230730T190000, start_date=20230730T200015, end_date=20230730T200037
[2023-07-30T20:00:37.385+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 78 for task S6 (Waiter StepComplete failed: Max attempts exceeded; 3453)
[2023-07-30T20:00:37.421+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-30T20:00:37.440+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
