[2023-08-02T18:00:16.018+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-02T18:00:16.074+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: userCase2.validate_file scheduled__2023-08-02T17:00:00+00:00 [queued]>
[2023-08-02T18:00:16.086+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: userCase2.validate_file scheduled__2023-08-02T17:00:00+00:00 [queued]>
[2023-08-02T18:00:16.086+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-02T18:00:16.100+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_file> on 2023-08-02 17:00:00+00:00
[2023-08-02T18:00:16.108+0000] {standard_task_runner.py:57} INFO - Started process 3660 to run task
[2023-08-02T18:00:16.111+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'userCase2', 'validate_file', 'scheduled__2023-08-02T17:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/userCase.py', '--cfg-path', '/tmp/tmp7q9kpm9e']
[2023-08-02T18:00:16.114+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask validate_file
[2023-08-02T18:00:16.127+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-02T18:00:16.165+0000] {task_command.py:410} INFO - Running <TaskInstance: userCase2.validate_file scheduled__2023-08-02T17:00:00+00:00 [running]> on host 484e6be077e8
[2023-08-02T18:00:16.176+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-02T18:00:16.245+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='userCase2' AIRFLOW_CTX_TASK_ID='validate_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-02T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-02T17:00:00+00:00'
[2023-08-02T18:00:16.247+0000] {logging_mixin.py:150} INFO - Reading the file
[2023-08-02T18:00:16.264+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2023-08-02T18:00:16.395+0000] {logging_mixin.py:150} INFO - userId,movieId,rating,timestamp
[2023-08-02T18:00:16.395+0000] {logging_mixin.py:150} INFO - 1,31,2.5,1260759144
[2023-08-02T18:00:16.396+0000] {logging_mixin.py:150} INFO - 1,1029,3.0,1260759179
[2023-08-02T18:00:16.396+0000] {logging_mixin.py:150} INFO - 1,1061,3.0,1260759182
[2023-08-02T18:00:16.396+0000] {logging_mixin.py:150} INFO - 1,1129,2.0,1260759185
[2023-08-02T18:00:16.396+0000] {logging_mixin.py:150} INFO - 1,1172,4.0,1260759205
[2023-08-02T18:00:16.396+0000] {logging_mixin.py:150} INFO - 1,1263,2.0,1260759151
[2023-08-02T18:00:16.396+0000] {logging_mixin.py:150} INFO - 1,1287,2.0,1260759187
[2023-08-02T18:00:16.396+0000] {logging_mixin.py:150} INFO - 1,1293,2.0,1260759148
[2023-08-02T18:00:16.397+0000] {logging_mixin.py:150} INFO - 1,1339,3.5,1260759125
[2023-08-02T18:00:16.397+0000] {logging_mixin.py:150} INFO - 1,1343,2.0,1260759131
[2023-08-02T18:00:16.397+0000] {logging_mixin.py:150} INFO - 1,1371,2.5,1260759135
[2023-08-02T18:00:16.397+0000] {logging_mixin.py:150} INFO - 1,1405,1.0,1260759203
[2023-08-02T18:00:16.397+0000] {logging_mixin.py:150} INFO - 1,1953,4.0,1260759191
[2023-08-02T18:00:16.397+0000] {logging_mixin.py:150} INFO - 1,2105,4.0,1260759139
[2023-08-02T18:00:16.397+0000] {logging_mixin.py:150} INFO - 1,2150,3.0,1260759194
[2023-08-02T18:00:16.398+0000] {logging_mixin.py:150} INFO - 1,2193,2.0,1260759198
[2023-08-02T18:00:16.398+0000] {logging_mixin.py:150} INFO - 1,2294,2.0,1260759108
[2023-08-02T18:00:16.398+0000] {logging_mixin.py:150} INFO - 1,2455,2.5,1260759113
[2023-08-02T18:00:16.398+0000] {logging_mixin.py:150} INFO - 1,2968,1.0,1260759200
[2023-08-02T18:00:16.399+0000] {python.py:183} INFO - Done. Returned value was: True
[2023-08-02T18:00:16.427+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=userCase2, task_id=validate_file, execution_date=20230802T170000, start_date=20230802T180016, end_date=20230802T180016
[2023-08-02T18:00:16.485+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-02T18:00:16.503+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
