[2023-08-12T20:00:28.087+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-12T20:00:28.159+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: userCase2.renameFile scheduled__2023-08-12T19:00:00+00:00 [queued]>
[2023-08-12T20:00:28.169+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: userCase2.renameFile scheduled__2023-08-12T19:00:00+00:00 [queued]>
[2023-08-12T20:00:28.169+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-12T20:00:28.187+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): renameFile> on 2023-08-12 19:00:00+00:00
[2023-08-12T20:00:28.195+0000] {standard_task_runner.py:57} INFO - Started process 17083 to run task
[2023-08-12T20:00:28.199+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'userCase2', 'renameFile', 'scheduled__2023-08-12T19:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/userCase.py', '--cfg-path', '/tmp/tmpunitby_j']
[2023-08-12T20:00:28.202+0000] {standard_task_runner.py:85} INFO - Job 263: Subtask renameFile
[2023-08-12T20:00:28.218+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-12T20:00:28.258+0000] {task_command.py:410} INFO - Running <TaskInstance: userCase2.renameFile scheduled__2023-08-12T19:00:00+00:00 [running]> on host 484e6be077e8
[2023-08-12T20:00:28.270+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-12T20:00:28.343+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='userCase2' AIRFLOW_CTX_TASK_ID='renameFile' AIRFLOW_CTX_EXECUTION_DATE='2023-08-12T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-12T19:00:00+00:00'
[2023-08-12T20:00:28.345+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-12T20:00:28.346+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 's3_buckName="myawsbucket19080"\ns3_location="raw/movies.csv"\ns3_file_name_without_ext=${s3_location%.*}\ns3_file_ext=${s3_location: -4}\nexport AWS_ACCESS_KEY_ID=AKIAYJC6EOICLIH36STV\nexport AWS_SECRET_ACCESS_KEY=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\ntimestamp=20230812T190000\n#timestamp="02092023120101"\naws s3 mv  s3://${s3_buckName}/${s3_location}   s3://${s3_buckName}/${s3_file_name_without_ext}_${timestamp}_validated${s3_file_ext}']
[2023-08-12T20:00:28.360+0000] {subprocess.py:86} INFO - Output:
[2023-08-12T20:00:28.362+0000] {subprocess.py:93} INFO - /bin/bash: line 9: aws: command not found
[2023-08-12T20:00:28.363+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-12T20:00:28.375+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-12T20:00:28.379+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=userCase2, task_id=renameFile, execution_date=20230812T190000, start_date=20230812T200028, end_date=20230812T200028
[2023-08-12T20:00:28.392+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 263 for task renameFile (Bash command failed. The command returned a non-zero exit code 127.; 17083)
[2023-08-12T20:00:28.411+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-12T20:00:28.437+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
