[2023-08-13T06:55:49.331+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emrPipeline.renameFile manual__2023-08-13T06:55:18+00:00 [queued]>
[2023-08-13T06:55:49.340+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emrPipeline.renameFile manual__2023-08-13T06:55:18+00:00 [queued]>
[2023-08-13T06:55:49.340+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-13T06:55:49.357+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): renameFile> on 2023-08-13 06:55:18+00:00
[2023-08-13T06:55:49.364+0000] {standard_task_runner.py:57} INFO - Started process 6818 to run task
[2023-08-13T06:55:49.368+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'emrPipeline', 'renameFile', 'manual__2023-08-13T06:55:18+00:00', '--job-id', '514', '--raw', '--subdir', 'DAGS_FOLDER/emr.py', '--cfg-path', '/tmp/tmpthfsreyv']
[2023-08-13T06:55:49.396+0000] {standard_task_runner.py:85} INFO - Job 514: Subtask renameFile
[2023-08-13T06:55:49.452+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-13T06:55:49.554+0000] {task_command.py:410} INFO - Running <TaskInstance: emrPipeline.renameFile manual__2023-08-13T06:55:18+00:00 [running]> on host 484e6be077e8
[2023-08-13T06:55:49.823+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emrPipeline' AIRFLOW_CTX_TASK_ID='renameFile' AIRFLOW_CTX_EXECUTION_DATE='2023-08-13T06:55:18+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-13T06:55:18+00:00'
[2023-08-13T06:55:49.825+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-13T06:55:49.826+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'env']
[2023-08-13T06:55:49.827+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    self.sub_process = Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1757, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/usr/local/lib/python3.9/os.py", line 810, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-08-13T06:55:49.846+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=emrPipeline, task_id=renameFile, execution_date=20230813T065518, start_date=20230813T065549, end_date=20230813T065549
[2023-08-13T06:55:49.864+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 514 for task renameFile (expected str, bytes or os.PathLike object, not NoneType; 6818)
[2023-08-13T06:55:49.904+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-13T06:55:49.930+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
