[2023-08-14T16:16:35.866+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emrPipeline.cluster_remover manual__2023-08-14T16:15:24+00:00 [queued]>
[2023-08-14T16:16:35.879+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emrPipeline.cluster_remover manual__2023-08-14T16:15:24+00:00 [queued]>
[2023-08-14T16:16:35.879+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-14T16:16:35.893+0000] {taskinstance.py:1327} INFO - Executing <Task(EmrTerminateJobFlowOperator): cluster_remover> on 2023-08-14 16:15:24+00:00
[2023-08-14T16:16:35.900+0000] {standard_task_runner.py:57} INFO - Started process 9902 to run task
[2023-08-14T16:16:35.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'emrPipeline', 'cluster_remover', 'manual__2023-08-14T16:15:24+00:00', '--job-id', '1469', '--raw', '--subdir', 'DAGS_FOLDER/emr.py', '--cfg-path', '/tmp/tmpitn9jejb']
[2023-08-14T16:16:35.907+0000] {standard_task_runner.py:85} INFO - Job 1469: Subtask cluster_remover
[2023-08-14T16:16:35.920+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-14T16:16:35.968+0000] {task_command.py:410} INFO - Running <TaskInstance: emrPipeline.cluster_remover manual__2023-08-14T16:15:24+00:00 [running]> on host d4028c5ba2ac
[2023-08-14T16:16:36.133+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emrPipeline' AIRFLOW_CTX_TASK_ID='cluster_remover' AIRFLOW_CTX_EXECUTION_DATE='2023-08-14T16:15:24+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-14T16:15:24+00:00'
[2023-08-14T16:16:36.145+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-08-14T16:16:36.146+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-08-14T16:16:36.715+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/emr.py", line 898, in execute
    log_uri=get_log_uri(emr_client=emr, job_flow_id=self.job_flow_id),
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/links/emr.py", line 62, in get_log_uri
    cluster_info = (cluster or emr_client.describe_cluster(ClusterId=job_flow_id))["Cluster"]
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the DescribeCluster operation: Cluster id 'None' is not valid.
[2023-08-14T16:16:36.732+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=emrPipeline, task_id=cluster_remover, execution_date=20230814T161524, start_date=20230814T161635, end_date=20230814T161636
[2023-08-14T16:16:36.744+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1469 for task cluster_remover (An error occurred (InvalidRequestException) when calling the DescribeCluster operation: Cluster id 'None' is not valid.; 9902)
[2023-08-14T16:16:36.766+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-14T16:16:36.805+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
