[2023-08-13T18:00:20.881+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-13T18:00:20.971+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: userCase2.s3_file_check scheduled__2023-08-13T17:00:00+00:00 [queued]>
[2023-08-13T18:00:20.981+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: userCase2.s3_file_check scheduled__2023-08-13T17:00:00+00:00 [queued]>
[2023-08-13T18:00:20.982+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-08-13T18:00:21.008+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): s3_file_check> on 2023-08-13 17:00:00+00:00
[2023-08-13T18:00:21.016+0000] {standard_task_runner.py:57} INFO - Started process 13317 to run task
[2023-08-13T18:00:21.022+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'userCase2', 's3_file_check', 'scheduled__2023-08-13T17:00:00+00:00', '--job-id', '1099', '--raw', '--subdir', 'DAGS_FOLDER/userCase.py', '--cfg-path', '/tmp/tmp0_velf52']
[2023-08-13T18:00:21.025+0000] {standard_task_runner.py:85} INFO - Job 1099: Subtask s3_file_check
[2023-08-13T18:00:21.038+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-13T18:00:21.082+0000] {task_command.py:410} INFO - Running <TaskInstance: userCase2.s3_file_check scheduled__2023-08-13T17:00:00+00:00 [running]> on host 484e6be077e8
[2023-08-13T18:00:21.093+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-13T18:00:21.184+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='userCase2' AIRFLOW_CTX_TASK_ID='s3_file_check' AIRFLOW_CTX_EXECUTION_DATE='2023-08-13T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-13T17:00:00+00:00'
[2023-08-13T18:00:21.185+0000] {s3.py:103} INFO - Poking for key : s3://myawsbucket19080/raw/movies.csv
[2023-08-13T18:00:21.196+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-08-13T18:00:21.196+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-08-13T18:00:31.759+0000] {s3.py:103} INFO - Poking for key : s3://myawsbucket19080/raw/movies.csv
[2023-08-13T18:00:41.819+0000] {s3.py:103} INFO - Poking for key : s3://myawsbucket19080/raw/movies.csv
[2023-08-13T18:00:51.859+0000] {s3.py:103} INFO - Poking for key : s3://myawsbucket19080/raw/movies.csv
[2023-08-13T18:00:51.915+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 141, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 30.73008443499566 seconds exceeds the specified timeout of 30.
[2023-08-13T18:00:51.924+0000] {taskinstance.py:1345} INFO - Immediate failure requested. Marking task as FAILED. dag_id=userCase2, task_id=s3_file_check, execution_date=20230813T170000, start_date=20230813T180020, end_date=20230813T180051
[2023-08-13T18:00:51.936+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1099 for task s3_file_check (Sensor has timed out; run duration of 30.73008443499566 seconds exceeds the specified timeout of 30.; 13317)
[2023-08-13T18:00:51.979+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-13T18:00:52.008+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
